<a href="https://colab.research.google.com/github/manabtikadar/my_project/blob/main/Research_paper_classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
!unzip /content/Reference-20250107T161046Z-001.zip -d /content/Papers

Archive:  /content/Reference-20250107T161046Z-001.zip
  inflating: /content/Papers/Reference/Non-Publishable/R004.pdf  
  inflating: /content/Papers/Reference/Non-Publishable/R003.pdf  
  inflating: /content/Papers/Reference/Non-Publishable/R005.pdf  
  inflating: /content/Papers/Reference/Non-Publishable/R002.pdf  
  inflating: /content/Papers/Reference/Publishable/TMLR/R014.pdf  
  inflating: /content/Papers/Reference/Publishable/NeurIPS/R013.pdf  
  inflating: /content/Papers/Reference/Non-Publishable/R001.pdf  
  inflating: /content/Papers/Reference/Publishable/NeurIPS/R012.pdf  
  inflating: /content/Papers/Reference/Publishable/KDD/R010.pdf  
  inflating: /content/Papers/Reference/Publishable/CVPR/R006.pdf  
  inflating: /content/Papers/Reference/Publishable/TMLR/R015.pdf  
  inflating: /content/Papers/Reference/Publishable/EMNLP/R009.pdf  
  inflating: /content/Papers/Reference/Publishable/KDD/R011.pdf  
  inflating: /content/Papers/Reference/Publishable/EMNLP/R008.pdf  
  infla

In [6]:
!pip install PyPDF2

In [7]:
import PyPDF2

def extract_text_from_pdf(pdf_file):
    with open(pdf_file, 'rb') as file:
        reader = PyPDF2.PdfReader(file)
        text = ''
        for page in range(len(reader.pages)):
            text += reader.pages[page].extract_text()
    return text

# Usage example
pdf_file = '/content/Papers/Reference/Non-Publishable/R001.pdf'
text = extract_text_from_pdf(pdf_file)
print(text)

Transdimensional Properties of Graphite in Relation
to Cheese Consumption on Tuesday Afternoons
Abstract
Graphite research has led to discoveries about dolphins and their penchant for
collecting rare flowers, which bloom only under the light of a full moon, while
simultaneously revealing the secrets of dark matter and its relation to the perfect
recipe for chicken parmesan, as evidenced by the curious case of the missing socks
in the laundry basket, which somehow correlates with the migration patterns of but-
terflies and the art of playing the harmonica underwater, where the sounds produced
are eerily similar to the whispers of ancient forests, whispering tales of forgotten
civilizations and their advanced understanding of quantum mechanics, applied to
the manufacture of sentient toasters that can recite Shakespearean sonnets, all of
which is connected to the inherent properties of graphite and its ability to conduct
the thoughts of extraterrestrial beings, who are known to communicat

In [8]:
import pandas as pd
import os

In [9]:
for root,dir,files in os.walk('/content/Papers/Reference/Publishable'):
  print(root, dir, files)

/content/Papers/Reference/Publishable ['EMNLP', 'NeurIPS', 'CVPR', 'TMLR', 'KDD'] []
/content/Papers/Reference/Publishable/EMNLP [] ['R008.pdf', 'R009.pdf']
/content/Papers/Reference/Publishable/NeurIPS [] ['R013.pdf', 'R012.pdf']
/content/Papers/Reference/Publishable/CVPR [] ['R006.pdf', 'R007.pdf']
/content/Papers/Reference/Publishable/TMLR [] ['R014.pdf', 'R015.pdf']
/content/Papers/Reference/Publishable/KDD [] ['R010.pdf', 'R011.pdf']


In [10]:
import os
import pandas as pd

papers = []
labels = []
id = []
conference = []

# Process Non-Publishable PDFs
for root, dirs, files in os.walk('/content/Papers/Reference/Non-Publishable'):
    for file in files:
        if file.endswith('.pdf'):
            pdf_file_path = os.path.join(root, file)
            text = extract_text_from_pdf(pdf_file_path)
            id.append(file)
            papers.append(text)
            labels.append(0)
            conference.append('null')

# Process Publishable PDFs
for root, dirs, files in os.walk('/content/Papers/Reference/Publishable'):
    for dir in dirs:
        conference_root = os.path.join(root, dir)
        for _, _, files in os.walk(conference_root):
            for file in files:
                if file.endswith('.pdf'):
                    file_path = os.path.join(conference_root, file)
                    text = extract_text_from_pdf(file_path)
                    id.append(file)
                    papers.append(text)
                    labels.append(1)
                    conference.append(dir)

# Create DataFrame
pdf_dict = {'ID': id, 'PDF': papers, 'Label': labels, 'Conference': conference}
pdf_df = pd.DataFrame(pdf_dict)

# Display the DataFrame
pdf_df.head()

ID                                                PDF  Label  \
0  R005.pdf  Analyzing Real-Time Group Coordination in\nAug...      0   
1  R001.pdf  Transdimensional Properties of Graphite in Rel...      0   
2  R004.pdf  AI-Driven Personalization in Online Education\...      0   
3  R002.pdf  Synergistic Convergence of Photosynthetic Path...      0   
4  R003.pdf  Deciphering the Enigmatic Properties of Metals...      0   

  Conference  
0       null  
1       null  
2       null  
3       null  
4       null

In [11]:
pdf_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15 entries, 0 to 14
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   ID          15 non-null     object
 1   PDF         15 non-null     object
 2   Label       15 non-null     int64 
 3   Conference  15 non-null     object
dtypes: int64(1), object(3)
memory usage: 608.0+ bytes


In [12]:
pdf_df

ID                                                PDF  Label  \
0   R005.pdf  Analyzing Real-Time Group Coordination in\nAug...      0   
1   R001.pdf  Transdimensional Properties of Graphite in Rel...      0   
2   R004.pdf  AI-Driven Personalization in Online Education\...      0   
3   R002.pdf  Synergistic Convergence of Photosynthetic Path...      0   
4   R003.pdf  Deciphering the Enigmatic Properties of Metals...      0   
5   R008.pdf  Advanced techniques for through and contextual...      1   
6   R009.pdf  The Importance of Written Explanations in\nAgg...      1   
7   R013.pdf  Generalization in ReLU Networks via Restricted...      1   
8   R012.pdf  Safe Predictors for Input-Output Specification...      1   
9   R006.pdf  Detailed Action Identification in Baseball Gam...      1   
10  R007.pdf  Advancements in 3D Food Modeling: A Review of ...      1   
11  R014.pdf  Addressing Min-Max Challenges in Nonconvex-Non...      1   
12  R015.pdf  Examining the Convergence of Denoising Diffusi...      1   
13  R010.pdf  Detecting Medication Usage in Parkinson’s Dise...      1   
14  R011.pdf  Addressing Popularity Bias with Popularity-Con...      1   

   Conference  
0        null  
1        null  
2        null  
3        null  
4        null  
5       EMNLP  
6       EMNLP  
7     NeurIPS  
8     NeurIPS  
9        CVPR  
10       CVPR  
11       TMLR  
12       TMLR  
13        KDD  
14        KDD

In [13]:
csv_file_path = '/content/papers.csv'
pdf_df.to_csv(csv_file_path,index=False)

In [14]:
df = pd.read_csv('/content/papers.csv')

In [15]:
df = df.sample(frac=1).reset_index(drop=True)

In [16]:
df.fillna('Non Publishable',inplace=True)

In [17]:
df

ID                                                PDF  Label  \
0   R012.pdf  Safe Predictors for Input-Output Specification...      1   
1   R006.pdf  Detailed Action Identification in Baseball Gam...      1   
2   R013.pdf  Generalization in ReLU Networks via Restricted...      1   
3   R009.pdf  The Importance of Written Explanations in\nAgg...      1   
4   R001.pdf  Transdimensional Properties of Graphite in Rel...      0   
5   R010.pdf  Detecting Medication Usage in Parkinson’s Dise...      1   
6   R003.pdf  Deciphering the Enigmatic Properties of Metals...      0   
7   R008.pdf  Advanced techniques for through and contextual...      1   
8   R007.pdf  Advancements in 3D Food Modeling: A Review of ...      1   
9   R011.pdf  Addressing Popularity Bias with Popularity-Con...      1   
10  R004.pdf  AI-Driven Personalization in Online Education\...      0   
11  R014.pdf  Addressing Min-Max Challenges in Nonconvex-Non...      1   
12  R002.pdf  Synergistic Convergence of Photosynthetic Path...      0   
13  R005.pdf  Analyzing Real-Time Group Coordination in\nAug...      0   
14  R015.pdf  Examining the Convergence of Denoising Diffusi...      1   

         Conference  
0           NeurIPS  
1              CVPR  
2           NeurIPS  
3             EMNLP  
4   Non Publishable  
5               KDD  
6   Non Publishable  
7             EMNLP  
8              CVPR  
9               KDD  
10  Non Publishable  
11             TMLR  
12  Non Publishable  
13  Non Publishable  
14             TMLR

In [18]:
df = df.sample(frac=1,random_state=42).reset_index(drop=True)

In [19]:
df.to_csv('/content/Papers.csv',index=False)

In [20]:
data = pd.read_csv('/content/Papers.csv')
print(data)

          ID                                                PDF  Label  \
0   R011.pdf  Addressing Popularity Bias with Popularity-Con...      1   
1   R014.pdf  Addressing Min-Max Challenges in Nonconvex-Non...      1   
2   R012.pdf  Safe Predictors for Input-Output Specification...      1   
3   R005.pdf  Analyzing Real-Time Group Coordination in\nAug...      0   
4   R010.pdf  Detecting Medication Usage in Parkinson’s Dise...      1   
5   R007.pdf  Advancements in 3D Food Modeling: A Review of ...      1   
6   R013.pdf  Generalization in ReLU Networks via Restricted...      1   
7   R006.pdf  Detailed Action Identification in Baseball Gam...      1   
8   R015.pdf  Examining the Convergence of Denoising Diffusi...      1   
9   R001.pdf  Transdimensional Properties of Graphite in Rel...      0   
10  R008.pdf  Advanced techniques for through and contextual...      1   
11  R004.pdf  AI-Driven Personalization in Online Education\...      0   
12  R002.pdf  Synergistic Convergence 

In [21]:
!pip install transformers

In [22]:
from transformers import BertTokenizer
import tensorflow as tf
from sklearn.model_selection import train_test_split

In [23]:
tokenizer = BertTokenizer.from_pretrained('bert-base-uncased')

# Tokenize function
def tokenize_texts(texts, max_length=512):
    return tokenizer(
        texts,
        padding='max_length',
        truncation=True,
        max_length=max_length,
        return_tensors='tf'
    )

/usr/local/lib/python3.10/dist-packages/huggingface_hub/utils/_auth.py:94: UserWarning: 
The secret `HF_TOKEN` does not exist in your Colab secrets.
To authenticate with the Hugging Face Hub, create a token in your settings tab (https://huggingface.co/settings/tokens), set it as secret in your Google Colab and restart your session.
You will be able to reuse this secret in all of your notebooks.
Please note that authentication is recommended but still optional to access public models or datasets.
  warnings.warn(


tokenizer_config.json:   0%|          | 0.00/48.0 [00:00<?, ?B/s]

vocab.txt:   0%|          | 0.00/232k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/466k [00:00<?, ?B/s]

config.json:   0%|          | 0.00/570 [00:00<?, ?B/s]

In [24]:
texts = df['PDF'].tolist()   # List of text from PDFs
labels = df['Label'].tolist()  # List of binary labels

labels_tensor = tf.convert_to_tensor(labels)

In [25]:
tokenized_data = tokenize_texts(texts)

In [26]:
print(tokenized_data)

{'input_ids': <tf.Tensor: shape=(15, 512), dtype=int32, numpy=
array([[  101, 12786,  6217, ...,  5664, 21641,   102],
       [  101, 12786,  8117, ...,  5214,  1997,   102],
       [  101,  3647, 16014, ...,  2275,  1997,   102],
       ...,
       [  101, 19962,  2121, ...,  2241,  2943,   102],
       [  101,  1996,  5197, ...,  1998,  1037,   102],
       [  101, 11703, 11514, ...,  1997, 12392,   102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(15, 512), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(15, 512), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=int32)>}

In [27]:
input_ids, attention_masks = tokenized_data['input_ids'], tokenized_data['attention_mask']
print(f"{input_ids}\n")
print(f"{attention_masks}\n")

[[  101 12786  6217 ...  5664 21641   102]
 [  101 12786  8117 ...  5214  1997   102]
 [  101  3647 16014 ...  2275  1997   102]
 ...
 [  101 19962  2121 ...  2241  2943   102]
 [  101  1996  5197 ...  1998  1037   102]
 [  101 11703 11514 ...  1997 12392   102]]

[[1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 ...
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]



In [28]:
X_train = (input_ids, attention_masks)
Y_train = labels_tensor

In [29]:
from transformers import TFBertModel
from tensorflow.keras import layers, Model

# Load pre-trained BERT model
bert_model = TFBertModel.from_pretrained('bert-base-uncased')

# Define the inputs
input_ids_layer = tf.keras.Input(shape=(512,), dtype=tf.int32, name='input_ids')
attention_mask_layer = tf.keras.Input(shape=(512,), dtype=tf.int32, name='attention_mask')

# Wrap the BERT model call in a Lambda layer and specify output_shape
bert_output = layers.Lambda(
    lambda x: bert_model(input_ids=x[0], attention_mask=x[1])[1],
    output_shape=(768,)  # Specify the output shape here (768 for 'bert-base-uncased')
)([input_ids_layer, attention_mask_layer])

# Add a classification head
output = layers.Dense(1, activation='sigmoid')(bert_output)

# Create the model
model = Model(inputs=[input_ids_layer, attention_mask_layer], outputs=output)

# Compile the model
model.compile(optimizer=tf.keras.optimizers.Adam(learning_rate=0.01),
              loss='binary_crossentropy', metrics=['accuracy'])

model.safetensors:   0%|          | 0.00/440M [00:00<?, ?B/s]

Some weights of the PyTorch model were not used when initializing the TF 2.0 model TFBertModel: ['cls.predictions.transform.LayerNorm.weight', 'cls.predictions.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.dense.bias', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.transform.LayerNorm.bias']
- This IS expected if you are initializing TFBertModel from a PyTorch model trained on another task or with another architecture (e.g. initializing a TFBertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing TFBertModel from a PyTorch model that you expect to be exactly identical (e.g. initializing a TFBertForSequenceClassification model from a BertForSequenceClassification model).
All the weights of TFBertModel were initialized from the PyTorch model.
If your task is similar to the task the model of the checkpoint was trained on, you can already use TFBertModel for predictions w

In [30]:
history = model.fit(
    x={'input_ids': X_train[0], 'attention_mask': X_train[1]},
    y=Y_train,
    epochs=10,
    batch_size=4
)

Epoch 1/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 57s 9s/step - accuracy: 0.4217 - loss: 1.2043
Epoch 2/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 44s 9s/step - accuracy: 0.6300 - loss: 0.6168
Epoch 3/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 39s 8s/step - accuracy: 0.6717 - loss: 0.6052
Epoch 4/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 40s 8s/step - accuracy: 0.6417 - loss: 0.6285
Epoch 5/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 41s 8s/step - accuracy: 0.7000 - loss: 0.5166
Epoch 6/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 41s 8s/step - accuracy: 0.7167 - loss: 0.4847
Epoch 7/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 36s 9s/step - accuracy: 0.7017 - loss: 0.4231
Epoch 8/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 34s 9s/step - accuracy: 0.6933 - loss: 0.5426
Epoch 9/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 42s 9s/step - accuracy: 0.7700 - loss: 0.4501
Epoch 10/10
4/4 ━━━━━━━━━━━━━━━━━━━━ 42s 9s/step - accuracy: 0.7667 - loss: 0.3760


In [31]:
prediction = model.predict({'input_ids': X_train[0], 'attention_mask': X_train[1]})

1/1 ━━━━━━━━━━━━━━━━━━━━ 46s 46s/step


In [32]:
print(prediction)

[[0.80557716]
 [0.98365307]
 [0.8805312 ]
 [0.7121085 ]
 [0.82129925]
 [0.7076091 ]
 [0.6272673 ]
 [0.8776345 ]
 [0.9534702 ]
 [0.46634662]
 [0.957771  ]
 [0.47339344]
 [0.44583923]
 [0.78626525]
 [0.4239007 ]]


In [33]:
prediction = tf.round(prediction)
print(prediction)
print(Y_train)

tf.Tensor(
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]], shape=(15, 1), dtype=float32)
tf.Tensor([1 1 1 0 1 1 1 1 1 0 1 0 0 1 0], shape=(15,), dtype=int32)


In [34]:
loss, accuracy = model.evaluate({'input_ids': X_train[0], 'attention_mask': X_train[1]}, Y_train)
print(f"Test Accuracy: {accuracy * 100:.2f}%")

1/1 ━━━━━━━━━━━━━━━━━━━━ 39s 39s/step - accuracy: 0.9333 - loss: 0.3658
Test Accuracy: 93.33%


In [35]:
import os.path
from os import path

model.save('pdf_classification_model.h5')
print(path.isfile('pdf_classification_model.h5'))
model_path = os.path.abspath('pdf_classification_model.h5')
print(model_path)

True
/content/pdf_classification_model.h5


In [36]:
!unzip /content/Papers-20250107T161145Z-001.zip -d /content/Papers_test

Archive:  /content/Papers-20250107T161145Z-001.zip
  inflating: /content/Papers_test/Papers/P049.pdf  
  inflating: /content/Papers_test/Papers/P101.pdf  
  inflating: /content/Papers_test/Papers/P042.pdf  
  inflating: /content/Papers_test/Papers/P083.pdf  
  inflating: /content/Papers_test/Papers/P004.pdf  
  inflating: /content/Papers_test/Papers/P112.pdf  
  inflating: /content/Papers_test/Papers/P079.pdf  
  inflating: /content/Papers_test/Papers/P010.pdf  
  inflating: /content/Papers_test/Papers/P109.pdf  
  inflating: /content/Papers_test/Papers/P012.pdf  
  inflating: /content/Papers_test/Papers/P057.pdf  
  inflating: /content/Papers_test/Papers/P054.pdf  
  inflating: /content/Papers_test/Papers/P089.pdf  
  inflating: /content/Papers_test/Papers/P014.pdf  
  inflating: /content/Papers_test/Papers/P052.pdf  
  inflating: /content/Papers_test/Papers/P095.pdf  
  inflating: /content/Papers_test/Papers/P131.pdf  
  inflating: /content/Papers_test/Papers/P103.pdf  
  inflating: 

In [37]:
import os
import pandas as pd

papers = []
id = []

# Process Non-Publishable PDFs
for root, dirs, files in os.walk('/content/Papers_test/Papers'):
    for file in files:
        if file.endswith('.pdf'):
            pdf_file_path = os.path.join(root, file)
            text = extract_text_from_pdf(pdf_file_path)
            id.append(file)
            papers.append(text)

# Create DataFrame
pdf_test = {'ID': id, 'PDF': papers}
pdf_test = pd.DataFrame(pdf_test)
pdf_test.head()

ID                                                PDF
0  P085.pdf  Privacy Evaluation in Tabular Synthetic Data:\...
1  P006.pdf  High-Throughput Genomic Sequencing in Marine\n...
2  P127.pdf  Examining Machine Learning’s Impact on Persona...
3  P044.pdf  A Comprehensive Multimodal Dataset for\nClimat...
4  P008.pdf  Optimized Transfer Learning with Equivariant\n...

In [38]:
csv_file_path = '/content/papers_test.csv'
pdf_test.to_csv(csv_file_path,index=False,escapechar='\\')

In [39]:
data_test = pd.read_csv('/content/papers_test.csv')
print(data_test)

           ID                                                PDF
0    P085.pdf  Privacy Evaluation in Tabular Synthetic Data:\...
1    P006.pdf  High-Throughput Genomic Sequencing in Marine\n...
2    P127.pdf  Examining Machine Learning’s Impact on Persona...
3    P044.pdf  A Comprehensive Multimodal Dataset for\nClimat...
4    P008.pdf  Optimized Transfer Learning with Equivariant\n...
..        ...                                                ...
130  P004.pdf  Graph Neural Networks Without Training: Harnes...
131  P071.pdf  The Significance of Fillers in Textual Represe...
132  P098.pdf  Blockchain-Based Carbon Trading Platforms: A N...
133  P123.pdf  Acquiring Cross-Domain Representations for\nCo...
134  P112.pdf  Learning Genomic Sequence Representations usin...

[135 rows x 2 columns]


In [40]:
texts = data_test['PDF'].tolist()
tokenized_data_test = tokenize_texts(texts)
print(tokenized_data_test)

{'input_ids': <tf.Tensor: shape=(135, 512), dtype=int32, numpy=
array([[  101,  9394,  9312, ...,  2015,  1007,   102],
       [  101,  2152,  1011, ...,  8478,  5919,   102],
       [  101, 12843,  3698, ...,  1012,  2944,   102],
       ...,
       [  101,  3796, 24925, ...,  2037,  3169,   102],
       [  101, 13868,  2892, ...,  2079,  2025,   102],
       [  101,  4083,  8991, ...,  2731,  1999,   102]], dtype=int32)>, 'token_type_ids': <tf.Tensor: shape=(135, 512), dtype=int32, numpy=
array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int32)>, 'attention_mask': <tf.Tensor: shape=(135, 512), dtype=int32, numpy=
array([[1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       ...,
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1],
       [1, 1, 1, ..., 1, 1, 1]], dtype=int32

In [41]:
input_ids_test, attention_masks_test = tokenized_data_test['input_ids'], tokenized_data_test['attention_mask']
X_test = (input_ids_test, attention_masks_test)

In [42]:
prediction_test = model.predict({'input_ids': X_test[0], 'attention_mask': X_test[1]})

5/5 ━━━━━━━━━━━━━━━━━━━━ 357s 66s/step


In [43]:
prediction_test = tf.round(prediction_test)
print(prediction_test)

tf.Tensor(
[[1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [0.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]
 [1.]], shape=(135, 1), dtype=float32)


In [52]:
import numpy as np
prediction_test_array = np.array(prediction_test)  # Convert to NumPy array
print(prediction_test_array.shape)               # Now you can access shape
prediction_test = prediction_test_array.tolist()       # Convert back to list if needed
# print(prediction_test.shape)                    # Avoid this line for lists
print(len(prediction_test))

(135, 1)
135


In [61]:
import os
import pandas as pd

papers = []
id = []
Labels = []
predicted_label = []

# Process Non-Publishable PDFs
for root, dirs, files in os.walk('/content/Papers_test/Papers'):
    for i, file in enumerate(files):
        if file.endswith('.pdf'):
            pdf_file_path = os.path.join(root, file)
            text = extract_text_from_pdf(pdf_file_path)  # Function to extract text from PDF
            id.append(file)
            papers.append(text)
            Labels.append(prediction_test[i])  # Assuming prediction_test contains the labels
            if (prediction_test[i] == 0):
              predicted_label.append('Non-Publishable')
            else:
              predicted_label.append('Publishable')
# Create DataFrame
pdf_test = pd.DataFrame({'ID': id, 'PDF': papers, 'Label': Labels, 'Predicted_label': predicted_label})

# Display first few rows
pdf_test.head()

ID                                                PDF  Label  \
0  P085.pdf  Privacy Evaluation in Tabular Synthetic Data:\...  [1.0]   
1  P006.pdf  High-Throughput Genomic Sequencing in Marine\n...  [1.0]   
2  P127.pdf  Examining Machine Learning’s Impact on Persona...  [1.0]   
3  P044.pdf  A Comprehensive Multimodal Dataset for\nClimat...  [1.0]   
4  P008.pdf  Optimized Transfer Learning with Equivariant\n...  [1.0]   

  Predicted_label  
0     Publishable  
1     Publishable  
2     Publishable  
3     Publishable  
4     Publishable

In [62]:
pdf_test

ID                                                PDF  Label  \
0    P085.pdf  Privacy Evaluation in Tabular Synthetic Data:\...  [1.0]   
1    P006.pdf  High-Throughput Genomic Sequencing in Marine\n...  [1.0]   
2    P127.pdf  Examining Machine Learning’s Impact on Persona...  [1.0]   
3    P044.pdf  A Comprehensive Multimodal Dataset for\nClimat...  [1.0]   
4    P008.pdf  Optimized Transfer Learning with Equivariant\n...  [1.0]   
..        ...                                                ...    ...   
130  P004.pdf  Graph Neural Networks Without Training: Harnes...  [1.0]   
131  P071.pdf  The Significance of Fillers in Textual Represe...  [1.0]   
132  P098.pdf  Blockchain-Based Carbon Trading Platforms: A N...  [1.0]   
133  P123.pdf  Acquiring Cross-Domain Representations for\nCo...  [1.0]   
134  P112.pdf  Learning Genomic Sequence Representations usin...  [1.0]   

    Predicted_label  
0       Publishable  
1       Publishable  
2       Publishable  
3       Publishable  
4       Publishable  
..              ...  
130     Publishable  
131     Publishable  
132     Publishable  
133     Publishable  
134     Publishable  

[135 rows x 4 columns]

In [64]:
pdf_test.to_csv('/content/Papers_test_prediction.csv',index=False,escapechar='\\')

In [60]:
num_zeros = pdf_test['Label'].value_counts().get(1, 0)  # Count occurrences of 0, default to 0 if not found
num_ones = pdf_test['Label'].value_counts().get(0, 0)  # Count occurrences of 1, default to 0 if not found

print(f"Number of 0's: {num_zeros}")
print(f"Number of 1's: {num_ones}")

Number of 0's: 2
Number of 1's: 133


<ipython-input-60-8a566ea9def5>:1: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  num_zeros = pdf_test['Label'].value_counts().get(1, 0)  # Count occurrences of 0, default to 0 if not found
<ipython-input-60-8a566ea9def5>:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  num_ones = pdf_test['Label'].value_counts().get(0, 0)  # Count occurrences of 1, default to 0 if not found
